---
title: "finalPSY6422"
format: html
editor: visual
---

## Orla O'Shea PSY6422 Project

## Longitudinal trends in attainment of GCSEs in English and Maths across England, 2016-2024.

### Overview

This dataset was published through the Office for National Statistics (ONS), and was collected by the Department for Education by matching data from the School Census, information provided by the Awarding Organisation, and information provided by the Individualised Learner Record Database

The variable on the X axis shows the academic years from 2016 to 2024, which will indicate change over time.

The variables on the Y axis represent the division of England into lower tier/unitary authorities, such as city councils and London's borough councils. This was determined by what local authority individuals attended school in by the time they left at the age of 16. I decided to use these variables rather than vaster areas as it is more representative.

The constant/measurement represents the percentage of the population of the area who by the age of 19 had achieved a GCSE (or equivalent Level 2 qualification) in both Mathematics and either English Language and/or Literature.

#### *Research questions:*

-   Is there a general trend over time for the attainment of GCSEs in Maths and English at a national level?

-   Did the COVID-19 pandemic affect the attainment of these qualifications, and why might this be?

### Data Preparation

The ONS already has their data cleaned and aggregated, such as being cross-checked for outliers and missing values. I cleaned the .csv file to separate the data into columns as they had all merged into one, before converting from wide to long format and then mutating it into numeric form as it originally was character data.

INSERT CODE TO PROVE THIS

#### *Summary statistics:*

INSERT SUMMARY STATISTICS AND CODE FOR THIS

### Repository Structure, including visualisation.

data/ : Contains the raw dataset (gcses-and-equivalent-in-english-and-maths-table-data.csv)

analysis.qmd : Code and narrative via Quarto

analysis.html: Rendered output file

### Prerequisites

Install the following before reproducing this analysis (using the install.packages command):

tidyverse

dplyr

tidyr

ggplot2

plotly

### Heatmaps

# Project Script {style="line-height: 1.2;"}

Below is the final script with relevant narrative that produces the heatmap visualisation:

```{r}
library(dplyr) 
library(tidyr) #Both packages allowed me to clean the data before visualising it.

#I had to remove the first few headings to make sure the data read correctly,
#and then separated the variable columns from the data as they had merged together.
df <- read.csv("gcses-and-equivalent-in-english-and-maths-table-data.csv", 
               skip = 7, 
               header = FALSE, 
               quote = "\"", 
               sep = ",")
names(df) <- c("Area code","Area name","2016-17","2017-18","2018-19", "2019-20","2020-21","2021-22","2022-23","2023-24")

#Accounting for a space mark in one of the headings.
df <- df %>% filter(`Area code` != "Area code")

#Had to separate the data for each year which had also merged together.
df_long <- df %>% 
  pivot_longer( 
    cols = `2016-17`:`2023-24`, 
    names_to = "Year", 
    values_to = "Value")

#Converted from a wide to a long dataset so that I could demonstrate change over time,
#rather than focus on regional trends.
#The numbers were originally down as character rather than numeric data, and cleaned 
#the data to remove N/A values that weren't converted.
df_long <- df_long %>% mutate(Value = as.numeric(Value))
df_long_clean <- df_long %>% 
  mutate(Value = as.numeric(Value)) %>% 
  filter(!is.na(Value))

library(ggplot2)
library(tidyverse)
library(plotly) #These packages allowed me to visualise the data and make it interactive.

#I wanted to create a heatmap to communicate the bigger picture, demonstrating 
#trends over time but also accounting for regional differences.
df_heatmap <- df_long_clean %>%
  mutate(`Area name` = fct_reorder(`Area name`, Value, .fun = 'mean')) %>%
#Mutated the y-axis so it would be shown from highest to lowest regional percentages
#rather than alphabetically.
  ggplot(mapping = aes(x = Year, y = `Area name`, fill = Value)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma", direction = -1) +
#Wanted the darker colours to represent higher percentages and vice versa.
  labs(title = "Attainment of GCSEs in English and Maths across England",
       x = "Year", y = "Lower-tier/Unitary Authority", fill = "Pass Rate") +
  theme(axis.text.y = element_text(size = 4))

df_heatmap

df_heatmap +
  theme_minimal() +
  theme(
    legend.position = "right",
    plot.title = element_text(size = 11, face = "bold"),
    axis.title = element_text(size = 8),
    panel.grid.minor = element_blank()
  )

#Made the heatmap longer in order to leave spaces between the y-axis variables,
#and used the plotly package to make the map interactive so you can get the specific
#percentages of qualifications for each region per academic year.
ggplotly(df_heatmap, height = 1600)
```

### Summary

From looking at my visualisation, I have learned that across England there has been a general upward trend in the achievement of GCSEs in both English and Maths (or equivalent) since 2016. The heatmap suggests that the majority of the country's population obtain the relevant Level 2 qualifications by the time they turn 19. There is an overall decrease in the pass rate for the 2019-20 cohort which reflects those who were due to sit GCSE exams (and equivalent) during the COVID-19 pandemic - this is a reliable trend as it reflects the centre assessed grades or Ofqual-calculated grades that pupils' qualifications were dependent on for that year.

The pass rate for the 2022-23 cohort is particularly dense, possibly reflecting the choice for the Department of Education and national exam boards to use advanced information schemes for pupils' exams to make up for lost learning due to the pandemic.

In terms of skills, this project has taught me how to carefully choose and then mutate a dataset, before going on to visualise it through coding into an appropriate graph - in this case a heatmap. The project has allowed me to develop technical skills through ggplot2 and the tidyverse, as well as my analytical skillset in order to communicate data in a reproducible and engaging manner.

Next time, with further skills and research, I would aim to communicate regional differences in the data more explictly, rather than relying on inference to identify trends from the heatmap and dataset.Running Code
